// Generated by tools/sync-version.js from package.json — do not edit by hand.
// Single source of truth for the user-visible version string (sidebar
// marker, Info page "About" block). Regenerate with: npm run version:sync
window.YAPDP_VERSION = "0.2.0";
